services:
  postgres:
    container_name: postgres
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    depends_on:
      - backend 
    networks:
      - backend-network
