services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      target: ${NODE_ENV:-development} # Default to development target
    volumes:
      - ${VOLUME_MOUNT:-.}:/app  # Default to mounting the current directory (unset VOLUME_MOUNT for production)
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - backend-network
      
networks:
  backend-network:
